-- NOT APPLIED. PostgreSQL push store baseline, reviewed before cutover.
BEGIN;

    create table tb_push_dispatch (
        admin_only boolean,
        recipient_count integer not null,
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        created_by bigint not null,
        push_dispatch_id bigint generated by default as identity,
        app_variant varchar(20) not null check (app_variant in ('DEV','PREVIEW','PRODUCTION')),
        mode varchar(20) not null check (mode in ('TEST','ACTUAL')),
        audience varchar(24) not null check (audience in ('INTERNAL_TEST','LIVE','LEGACY_UNKNOWN')),
        status varchar(30) not null check (status in ('QUEUED','PROCESSING','COMPLETED','PARTIAL_FAILED','FAILED')),
        target_type varchar(30) not null check (target_type in ('INSTALLATION','USER','USER_GROUP','ALL')),
        action_type varchar(40) not null check (action_type in ('HOME','NOTICE','MY_PAGE','BUS_STOP','BUILDING_DETAIL','PLACE_DETAIL','CHARACTER_STORE','TEST')),
        notification_type varchar(40) not null check (notification_type in ('GENERAL')),
        target_value varchar(128) not null,
        idempotency_key varchar(160) not null,
        title varchar(200) not null,
        body varchar(1024) not null,
        image_url varchar(1024),
        action_params varchar(2048) not null,
        primary key (push_dispatch_id),
        constraint uk_push_dispatch_idempotency_key unique (idempotency_key)
    );

    create table tb_push_event_setting (
        enabled boolean not null,
        updated_at timestamp(6) not null,
        id varchar(100) not null,
        primary key (id)
    );

    create table tb_push_event_setting_change (
        enabled boolean not null,
        changed_at timestamp(6) not null,
        id bigint generated by default as identity,
        setting_id varchar(100) not null,
        changed_by varchar(255) not null,
        primary key (id)
    );

    create table tb_push_installation (
        active boolean not null,
        created_at timestamp(6),
        created_by bigint,
        deactivated_at timestamp(6),
        modified_at timestamp(6),
        modified_by bigint,
        push_installation_id bigint generated by default as identity,
        user_id bigint not null,
        app_variant varchar(20) not null check (app_variant in ('DEV','PREVIEW','PRODUCTION')),
        installation_id varchar(64) not null,
        expo_push_token varchar(255) not null,
        primary key (push_installation_id),
        constraint uk_push_installation_installation_id unique (installation_id),
        constraint uk_push_installation_expo_push_token unique (expo_push_token)
    );

    create table tb_push_message (
        receipt_attempts integer not null,
        send_attempts integer not null,
        created_at timestamp(6) not null,
        next_retry_at timestamp(6),
        push_dispatch_id bigint not null,
        push_installation_id bigint not null,
        push_message_id bigint generated by default as identity,
        receipt_available_at timestamp(6),
        receipt_checked_at timestamp(6),
        sent_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(30) not null check (status in ('QUEUED','SENDING','TICKET_RECEIVED','RECEIPT_PENDING','DELIVERED','FAILED')),
        receipt_status varchar(40),
        ticket_status varchar(40),
        installation_id varchar(64) not null,
        receipt_error varchar(1024),
        ticket_error varchar(1024),
        expo_ticket_id varchar(255),
        primary key (push_message_id)
    );

    create table tb_survey_push_schedule (
        reward_point integer not null,
        created_at timestamp(6) not null,
        processed_at timestamp(6),
        scheduled_at timestamp(6) not null,
        survey_push_schedule_id bigint generated by default as identity,
        target_user_id bigint,
        audience varchar(24) not null check (audience in ('INTERNAL_TEST','LIVE','LEGACY_UNKNOWN')),
        status varchar(30) not null check (status in ('PENDING','COMPLETED','CANCELLED','SKIPPED')),
        notification_stage varchar(40) not null check (notification_stage in ('STARTED','D_MINUS_3','DEADLINE','REMIND_AFTER_LATER')),
        survey_key varchar(64) not null,
        idempotency_key varchar(128) not null,
        primary key (survey_push_schedule_id),
        constraint uk_survey_push_schedule_idempotency_key unique (idempotency_key, audience)
    );

    create index idx_push_dispatch_status_created_at 
       on tb_push_dispatch (status, created_at);

    create index idx_push_installation_user_variant_active 
       on tb_push_installation (user_id, app_variant, active);

    create index idx_push_message_dispatch 
       on tb_push_message (push_dispatch_id);

    create index idx_push_message_status_next_retry_at 
       on tb_push_message (status, next_retry_at);

    create index idx_survey_push_schedule_status_scheduled_at 
       on tb_survey_push_schedule (status, scheduled_at);

    alter table if exists tb_push_message 
       add constraint FK6hhdmhsy5oi4fp94n88h2po17 
       foreign key (push_dispatch_id) 
       references tb_push_dispatch;

CREATE INDEX idx_push_dispatch_audience_created ON tb_push_dispatch (audience, created_at);
CREATE INDEX idx_push_survey_audience_due ON tb_survey_push_schedule (audience, status, scheduled_at);
COMMIT;
