spring:
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kodaero-release-database.c9mqymkk6lzc.ap-northeast-2.rds.amazonaws.com:3306/kodaero
    username: admin
    password: test1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
        encoding: UTF-8
  data:
    redis:
      host: 3.36.90.27
      # host: 43.202.47.183
      port: 6379
      password: 2804

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret:
    key: dG9kYXlpc2FwcmlsZm91cnRoaXRpc215ZnJpZW5ka2FuZ2hhZWppbnNiaXJ0aGRheQ==
  social:
    kakao:
      iss: https://kauth.kakao.com
      aud: 1b8e6e304906b7c01cdf8cc9e4d6ac3f
    google:
      iss: https://accounts.google.com
      aud: 567061659942-clomuj0g2t4o59560l63457v6bdlnpl0.apps.googleusercontent.com
    apple:
      iss: https://appleid.apple.com
      aud: com.kodaero.rn.dev
      dev-aud: com.kodaero.rn
  admin:
    token: devkorkodaero2024

cloud:
  aws:
    s3:
      bucket: kodaero-ku
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**

profile:
  image:
    lv1-url: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/profile/lv1.jpg
    lv2-url: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/profile/lv2.jpg
    lv3-url: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/profile/lv3.jpg
    lv4-url: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/profile/lv4.jpg
    lv5-url: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/profile/lv5.jpg

place:
  default-image:
    cafe: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/CAFE.jpg
    cafeteria: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/CAFETERIA.jpg
    convenience-store: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/CONVENIENCE_STORE.jpg
    gym: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/GYM.jpg
    lounge: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/LOUNGE.jpg
    reading-room: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/READING_ROOM.jpg
    shower-room: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/SHOWER_ROOM.jpg
    sleeping-room: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/SLEEPING_ROOM.jpg
    study-room: https://kodaero-ku.s3.ap-northeast-2.amazonaws.com/place/default_image/STUDY_ROOM.jpg

date:
  api:
    holiday:
      end-point: http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo
      encoded-key: RRDg18a7noGpfK%2F1rmFBRX8ms0%2BbAL0PO1VqCEhrWak%2BKISmaIZf%2BcHsT2FMSFtFnm%2FvLNlPtBrNZoWdTt6jfA%3D%3D
      decoded-key: RRDg18a7noGpfK/1rmFBRX8ms0+bAL0PO1VqCEhrWak+KISmaIZf+cHsT2FMSFtFnm/vLNlPtBrNZoWdTt6jfA==
