package devkor.com.teamcback.domain.chatbot.service;

import static org.bsc.langgraph4j.StateGraph.END; import static org.bsc.langgraph4j.StateGraph.START;
import devkor.com.teamcback.domain.chatbot.dto.*; import devkor.com.teamcback.domain.chatbot.gateway.LlmGateway; import devkor.com.teamcback.domain.chatbot.tool.CampusToolAdapter; import devkor.com.teamcback.domain.chatbot.tool.dto.*; import devkor.com.teamcback.domain.place.entity.PlaceType; import devkor.com.teamcback.global.exception.exception.GlobalException; import java.util.*; import org.bsc.langgraph4j.*; import org.bsc.langgraph4j.action.*; import org.bsc.langgraph4j.checkpoint.MemorySaver; import org.bsc.langgraph4j.state.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;

@Component @ConditionalOnProperty(prefix="chatbot",name="enabled",havingValue="true")
public class FacilityWorkflow {
 private static final String SEARCH="search",DECIDE="decide",ASK="ask",SELECT="select",LOAD="load",FORMAT="format",OWNER="owner",QUERY="query",TYPE="type",FLOOR="floor",INPUT="input",CANDIDATES="candidates",ID="id",NAME="name",REPLY="reply",WAITING="waiting",DATA="data";
 private final FacilityPlanner planner; private final CampusToolAdapter adapter; private final LocationCandidateSelector selector; private final MemorySaver saver=new MemorySaver(); private final CompiledGraph<State> graph;
 @Autowired public FacilityWorkflow(FacilityPlanner p,CampusToolAdapter a,LocationCandidateSelector s){planner=p;adapter=a;selector=s;try{StateGraph<State> g=new StateGraph<>(State.SCHEMA,State::new);g.addNode(SEARCH,AsyncNodeAction.node_async((NodeAction<State>)this::search));g.addNode(DECIDE,AsyncNodeAction.node_async((NodeAction<State>)this::decide));g.addNode(ASK,AsyncNodeAction.node_async((NodeAction<State>)this::ask));g.addNode(SELECT,AsyncNodeAction.node_async((NodeAction<State>)this::select));g.addNode(LOAD,AsyncNodeAction.node_async((NodeAction<State>)this::load));g.addNode(FORMAT,AsyncNodeAction.node_async((NodeAction<State>)this::format));g.addEdge(START,SEARCH);g.addEdge(SEARCH,DECIDE);g.addConditionalEdges(DECIDE,AsyncEdgeAction.edge_async((EdgeAction<State>)this::afterDecision),Map.of(ASK,ASK,LOAD,LOAD,END,END));g.addEdge(ASK,SELECT);g.addConditionalEdges(SELECT,AsyncEdgeAction.edge_async((EdgeAction<State>)this::afterSelect),Map.of(ASK,ASK,LOAD,LOAD));g.addEdge(LOAD,FORMAT);g.addEdge(FORMAT,END);graph=g.compile(CompileConfig.builder().checkpointSaver(saver).interruptAfter(ASK).releaseThread(true).build());}catch(GraphStateException e){throw new IllegalStateException("Unable to compile FACILITY workflow",e);}}
 public WorkflowResult handle(UUID id,ChatCaller caller,List<LlmGateway.ConversationMessage> history,String message){RunnableConfig c=config(id);var cp=graph.lastStateOf(c);State st;if(cp.isPresent()){owner(cp.get().state(),caller);st=run(GraphInput.resume(Map.of(INPUT,message)),c);}else{FacilityPlan p=planner.plan(history,message);if(p==null||!p.isFacility())return WorkflowResult.notHandled();Map<String,Object> in=new HashMap<>();in.put(OWNER,caller.key());in.put(QUERY,p.locationQuery()==null?"":p.locationQuery());in.put(TYPE,p.facilityType()==null?"":p.facilityType());in.put(FLOOR,p.floor()==null?"":String.valueOf(p.floor()));in.put(INPUT,message);st=run(GraphInput.args(in),c);}WorkflowResult r=new WorkflowResult(true,st.value(REPLY,""),!st.value(WAITING,"").isBlank());if(!r.waiting())release(c);return r;}
 public boolean hasPending(UUID id,ChatCaller c){var x=graph.lastStateOf(config(id));if(x.isEmpty())return false;owner(x.get().state(),c);return true;} public void cancel(UUID id,ChatCaller c){var x=graph.lastStateOf(config(id));if(x.isPresent()){owner(x.get().state(),c);release(config(id));}}
 private Map<String,Object> search(State s){String q=s.value(QUERY,"");List<Map<String,Object>> out=new ArrayList<>();if(!q.isBlank()){SearchCampusToolResult r=adapter.searchCampus(new SearchCampusToolRequest(q,5));if(r!=null&&r.candidates()!=null)for(SearchCampusItem i:r.candidates())if(i.locationType()==ToolLocationType.BUILDING)out.add(Map.of(ID,String.valueOf(i.locationId()),NAME,i.name()));}return Map.of(CANDIDATES,out,REPLY,out.isEmpty()&&q.isBlank()?"":"");}
 private Map<String,Object> decide(State s){List<Map<String,Object>> c=s.value(CANDIDATES,List.of());if(s.value(QUERY,"").isBlank())return Map.of(ID,"campus",WAITING,"");if(c.size()==1)return selected(c.get(0));if(c.size()>1)return Map.of(WAITING,"selection");return Map.of(REPLY,"요청한 건물을 찾지 못했어요.",WAITING,"");}
 private Map<String,Object> ask(State s){return Map.of(REPLY,"어느 건물의 시설인지 선택해 주세요: "+names(s));}
 private Map<String,Object> select(State s){List<Map<String,Object>> cs=s.value(CANDIDATES,List.of());List<LocationCandidateView> vs=new ArrayList<>();for(int i=0;i<cs.size();i++){Map<String,Object> c=cs.get(i);vs.add(new LocationCandidateView(i,String.valueOf(c.get(NAME)),ToolLocationType.BUILDING,"","",""));}LocationCandidateSelection x=selector.select(s.value(INPUT,""),vs);Integer i=x==null?null:x.candidateIndex();if(x!=null&&x.status()==CandidateSelection.Status.SELECTED&&i!=null&&i>=0&&i<cs.size())return selected(cs.get(i));return Map.of(WAITING,"selection",INPUT,"",REPLY,"후보 중 건물 이름을 정확히 골라 주세요: "+names(s));}
 private Map<String,Object> load(State s){try{CampusFacilityType t=facilityType(s.value(TYPE,""));if(t==null)return Map.of(REPLY,"지원하지 않는 시설 종류예요.",WAITING,"");Long b="campus".equals(s.value(ID,""))?null:Long.valueOf(s.value(ID,""));Integer f=s.value(FLOOR,"").isBlank()?null:Integer.valueOf(s.value(FLOOR,""));FindFacilitiesToolResult r=adapter.findFacilities(new FindFacilitiesToolRequest(t,b,f,10));return Map.of(DATA,facilityText(r),WAITING,"");}catch(IllegalArgumentException e){return Map.of(REPLY,"시설 종류나 층 정보가 올바르지 않아요.",WAITING,"");}}
 private Map<String,Object> format(State s){return Map.of(REPLY,s.value(DATA,""));}
 private String facilityText(FindFacilitiesToolResult r){if(r==null||r.error()!=null)return r==null?"시설 정보를 확인하지 못했어요.":r.error().message();return r.facilities().stream().map(x->x.name()+" ("+x.placeType()+", "+(x.floor()==null?"":x.floor()+"층")+")").reduce((a,b)->a+"\n"+b).orElse("검색된 시설이 없어요.");}
 private CampusFacilityType facilityType(String raw){if(raw==null||raw.isBlank())return null;String v=raw.trim().toUpperCase(Locale.ROOT);Map<String,String> alias=Map.of("화장실","TOILET","프린터","PRINTER","정수기","WATER_PURIFIER","카페","CAFE","식당","CAFETERIA","강의실","CLASSROOM");v=alias.getOrDefault(raw.trim(),v);return CampusFacilityType.valueOf(v);}
 private String afterDecision(State s){if(!s.value(REPLY,"").isBlank()&&!s.value(CANDIDATES,List.<Map<String,Object>>of()).isEmpty())return END;return s.value(ID,"").equals("campus")||!s.value(ID,"").isBlank()?LOAD:(s.value(CANDIDATES,List.<Map<String,Object>>of()).isEmpty()?END:ASK);}private String afterSelect(State s){return s.value(ID,"").isBlank()?ASK:LOAD;}private Map<String,Object> selected(Map<String,Object> c){return Map.of(ID,c.get(ID),NAME,c.get(NAME),WAITING,"");}private String names(State s){return s.value(CANDIDATES,List.<Map<String,Object>>of()).stream().map(c->String.valueOf(c.get(NAME))).distinct().reduce((a,b)->a+", "+b).orElse("");}private State run(GraphInput i,RunnableConfig c){try{return graph.invoke(i,c).orElseGet(()->graph.lastStateOf(c).orElseThrow().state());}catch(Exception e){throw new IllegalStateException("FACILITY workflow failed",e);}}private RunnableConfig config(UUID id){return RunnableConfig.builder().threadId("facility:"+id).build();}private void release(RunnableConfig c){try{saver.release(c);}catch(Exception e){throw new IllegalStateException(e);}}private void owner(State s,ChatCaller c){if(!c.key().equals(s.value(OWNER,"")))throw new GlobalException(devkor.com.teamcback.global.response.ResultCode.CHATBOT_SESSION_FORBIDDEN);}
 public record WorkflowResult(boolean handled,String reply,boolean waiting){static WorkflowResult notHandled(){return new WorkflowResult(false,null,false);}} public static final class State extends AgentState{static Channel<String> text(){return Channels.base(()->"");}static Channel<List<Map<String,Object>>> list(){return Channels.base(ArrayList::new);}static Channel<Object> obj(){return Channels.base(()->"");}static final Map<String,Channel<?>> SCHEMA=Map.ofEntries(Map.entry(OWNER,text()),Map.entry(QUERY,text()),Map.entry(TYPE,text()),Map.entry(FLOOR,text()),Map.entry(INPUT,text()),Map.entry(ID,text()),Map.entry(NAME,text()),Map.entry(REPLY,text()),Map.entry(WAITING,text()),Map.entry(CANDIDATES,list()),Map.entry(DATA,obj()));public State(Map<String,Object>d){super(d);}}
}
