package devkor.com.teamcback.domain.chatbot.service;
import static org.bsc.langgraph4j.StateGraph.END; import static org.bsc.langgraph4j.StateGraph.START;
import devkor.com.teamcback.domain.chatbot.dto.*; import devkor.com.teamcback.domain.chatbot.gateway.LlmGateway; import devkor.com.teamcback.domain.chatbot.tool.CampusToolAdapter; import devkor.com.teamcback.domain.chatbot.tool.dto.*; import devkor.com.teamcback.domain.place.entity.PlaceType; import devkor.com.teamcback.global.exception.exception.GlobalException; import java.util.*; import org.bsc.langgraph4j.*; import org.bsc.langgraph4j.action.*; import org.bsc.langgraph4j.checkpoint.MemorySaver; import org.bsc.langgraph4j.state.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;
@Component @ConditionalOnProperty(prefix="chatbot",name="enabled",havingValue="true") public class RoomCourseWorkflow {
 private static final String SEARCH="search",DECIDE="decide",ASK="ask",SELECT="select",LOAD="load",FORMAT="format",OWNER="owner",QUERY="query",DAY="day",INPUT="input",CANDIDATES="candidates",ID="id",NAME="name",REPLY="reply",WAITING="waiting",DATA="data";
 private final RoomCoursePlanner planner;private final CampusToolAdapter adapter;private final LocationCandidateSelector selector;private final MemorySaver saver=new MemorySaver();private final CompiledGraph<State> graph;
 @Autowired public RoomCourseWorkflow(RoomCoursePlanner p,CampusToolAdapter a,LocationCandidateSelector s){planner=p;adapter=a;selector=s;try{StateGraph<State> g=new StateGraph<>(State.SCHEMA,State::new);g.addNode(SEARCH,AsyncNodeAction.node_async((NodeAction<State>)this::search));g.addNode(DECIDE,AsyncNodeAction.node_async((NodeAction<State>)this::decide));g.addNode(ASK,AsyncNodeAction.node_async((NodeAction<State>)this::ask));g.addNode(SELECT,AsyncNodeAction.node_async((NodeAction<State>)this::select));g.addNode(LOAD,AsyncNodeAction.node_async((NodeAction<State>)this::load));g.addNode(FORMAT,AsyncNodeAction.node_async((NodeAction<State>)this::format));g.addEdge(START,SEARCH);g.addEdge(SEARCH,DECIDE);g.addConditionalEdges(DECIDE,AsyncEdgeAction.edge_async((EdgeAction<State>)this::afterDecision),Map.of(ASK,ASK,LOAD,LOAD,END,END));g.addEdge(ASK,SELECT);g.addConditionalEdges(SELECT,AsyncEdgeAction.edge_async((EdgeAction<State>)this::afterSelect),Map.of(ASK,ASK,LOAD,LOAD));g.addEdge(LOAD,FORMAT);g.addEdge(FORMAT,END);graph=g.compile(CompileConfig.builder().checkpointSaver(saver).interruptAfter(ASK).releaseThread(true).build());}catch(GraphStateException e){throw new IllegalStateException("Unable to compile ROOM_COURSE workflow",e);}}
 public WorkflowResult handle(UUID id,ChatCaller c,List<LlmGateway.ConversationMessage> h,String m){RunnableConfig rc=config(id);var cp=graph.lastStateOf(rc);State st;if(cp.isPresent()){owner(cp.get().state(),c);st=run(GraphInput.resume(Map.of(INPUT,m)),rc);}else{RoomCoursePlan p=planner.plan(h,m);if(p==null||!p.isRoomCourse())return WorkflowResult.notHandled();st=run(GraphInput.args(Map.of(OWNER,c.key(),QUERY,p.roomQuery(),DAY,p.weekdayExpression()==null?"":p.weekdayExpression(),INPUT,m)),rc);}WorkflowResult r=new WorkflowResult(true,st.value(REPLY,""),!st.value(WAITING,"").isBlank());if(!r.waiting())release(rc);return r;}
 public boolean hasPending(UUID id,ChatCaller c){var x=graph.lastStateOf(config(id));if(x.isEmpty())return false;owner(x.get().state(),c);return true;}public void cancel(UUID id,ChatCaller c){var x=graph.lastStateOf(config(id));if(x.isPresent()){owner(x.get().state(),c);release(config(id));}}
 private Map<String,Object> search(State s){SearchCampusToolResult r=adapter.searchCampus(new SearchCampusToolRequest(s.value(QUERY,""),5));List<Map<String,Object>> out=new ArrayList<>();if(r!=null&&r.candidates()!=null)for(SearchCampusItem i:r.candidates())if(i.locationType()==ToolLocationType.PLACE&&i.placeType()==PlaceType.CLASSROOM)out.add(Map.of(ID,String.valueOf(i.locationId()),NAME,i.name(),"buildingName",Objects.toString(i.buildingName(),""),"floor",Objects.toString(i.floor(),"")));return Map.of(CANDIDATES,out,REPLY,out.isEmpty()?"해당 강의실을 찾지 못했어요.":"");}
 private Map<String,Object> decide(State s){List<Map<String,Object>> c=s.value(CANDIDATES,List.of());if(c.size()==1)return selected(c.get(0));if(c.size()>1)return Map.of(WAITING,"selection");return Map.of(WAITING,"");}private Map<String,Object> ask(State s){return Map.of(REPLY,"어느 강의실인지 선택해 주세요: "+names(s));}
 private Map<String,Object> select(State s){List<Map<String,Object>> cs=s.value(CANDIDATES,List.of());List<LocationCandidateView> vs=new ArrayList<>();for(int i=0;i<cs.size();i++){Map<String,Object> c=cs.get(i);vs.add(new LocationCandidateView(i,String.valueOf(c.get(NAME)),ToolLocationType.PLACE,String.valueOf(c.get("buildingName")),String.valueOf(c.get("floor")),"CLASSROOM"));}LocationCandidateSelection x=selector.select(s.value(INPUT,""),vs);Integer i=x==null?null:x.candidateIndex();if(x!=null&&x.status()==CandidateSelection.Status.SELECTED&&i!=null&&i>=0&&i<cs.size())return selected(cs.get(i));return Map.of(WAITING,"selection",INPUT,"",REPLY,"후보 중 강의실 이름을 정확히 골라 주세요: "+names(s));}
 private Map<String,Object> load(State s){try{devkor.com.teamcback.domain.common.entity.Weekday d=WorkflowDates.weekday(s.value(DAY,""));GetRoomCoursesToolResult r=adapter.getRoomCourses(new GetRoomCoursesToolRequest(Long.valueOf(s.value(ID,"0")),d));return Map.of(DATA,roomText(r),WAITING,"");}catch(IllegalArgumentException e){return Map.of(REPLY,"요일 정보가 올바르지 않아요.",WAITING,"");}}
 private Map<String,Object> format(State s){return Map.of(REPLY,s.value(DATA,""));}
 private String roomText(GetRoomCoursesToolResult r){if(r==null||r.error()!=null)return r==null?"수업 정보를 확인하지 못했어요.":r.error().message();return r.room().roomName()+" 수업\n"+r.room().courses().stream().map(x->x.weekday()+" "+x.startPeriod()+"-"+x.endPeriod()+"교시: "+x.subject()+" / "+x.professor()).reduce((a,b)->a+"\n"+b).orElse("등록된 수업이 없어요.");}
 private String afterDecision(State s){return s.value(CANDIDATES,List.<Map<String,Object>>of()).isEmpty()?END:(!s.value(ID,"").isBlank()?LOAD:ASK);}private String afterSelect(State s){return s.value(ID,"").isBlank()?ASK:LOAD;}private Map<String,Object> selected(Map<String,Object> c){return Map.of(ID,c.get(ID),NAME,c.get(NAME),WAITING,"");}private String names(State s){return s.value(CANDIDATES,List.<Map<String,Object>>of()).stream().map(c->String.valueOf(c.get(NAME))).distinct().reduce((a,b)->a+", "+b).orElse("");}private State run(GraphInput i,RunnableConfig c){try{return graph.invoke(i,c).orElseGet(()->graph.lastStateOf(c).orElseThrow().state());}catch(Exception e){throw new IllegalStateException("ROOM_COURSE workflow failed",e);}}private RunnableConfig config(UUID id){return RunnableConfig.builder().threadId("room-course:"+id).build();}private void release(RunnableConfig c){try{saver.release(c);}catch(Exception e){throw new IllegalStateException(e);}}private void owner(State s,ChatCaller c){if(!c.key().equals(s.value(OWNER,"")))throw new GlobalException(devkor.com.teamcback.global.response.ResultCode.CHATBOT_SESSION_FORBIDDEN);}
 public record WorkflowResult(boolean handled,String reply,boolean waiting){static WorkflowResult notHandled(){return new WorkflowResult(false,null,false);}}public static final class State extends AgentState{static Channel<String> text(){return Channels.base(()->"");}static Channel<List<Map<String,Object>>> list(){return Channels.base(ArrayList::new);}static Channel<Object> obj(){return Channels.base(()->"");}static final Map<String,Channel<?>> SCHEMA=Map.of(OWNER,text(),QUERY,text(),DAY,text(),INPUT,text(),ID,text(),NAME,text(),REPLY,text(),WAITING,text(),CANDIDATES,list(),DATA,obj());public State(Map<String,Object>d){super(d);}}
}
